# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message="O n\xfamero de telefone precisa estar no formato: '+9999999999999'. At\xe9 14 digitos s\xe3o permitidos.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
