# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaTermino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nome_invalido', message='Nome invalido', regex='^[a-zA-Z *]+$')])),
                ('telefone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message='Numero de telefone invalido', regex='^\\(\\d\\d\\)\\d{5}-\\d{4}$')])),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_alugueis.Cliente'),
        ),
    ]
