# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 03:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_alugueis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.DateField()),
                ('horaInicio', models.DateField()),
                ('horaTermino', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message='Numero de telefone invalido', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_alugueis.Cliente'),
        ),
    ]
