# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_alugueis', '0003_auto_20161126_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='horaInicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='horaTermino',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message='Numero de telefone invalido', regex='^\\(\\d\\d\\)\\d{5}-\\d{4}$')]),
        ),
    ]
