# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('controle_alugueis', '0004_auto_20161126_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='horaTermino',
            field=models.TimeField(default=datetime.datetime(2016, 11, 26, 10, 6, 40, 785999, tzinfo=utc)),
        ),
    ]
