# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_alugueis', '0005_auto_20161126_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='horaTermino',
            field=models.TimeField(),
        ),
    ]
