# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=40)),
                ('done', models.BooleanField(default=False)),
                ('grau_importancia', models.IntegerField(choices=[(1, b'Urgente'), (2, b'Importante'), (3, b'Simples'), (4, b'Lembrete')], default=3)),
            ],
        ),
    ]
