# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.IntegerField(choices=[(1, b'Agua'), (2, b'Luz'), (3, b'Material de limpeza'), (4, b'Papelaria'), (5, b'Mobilia'), (6, b'Seguran\xc3\xa7a'), (7, b'Manuten\xc3\xa7\xc3\xa3o'), (8, b'Regulamenta\xc3\xa7\xc3\xa3o'), (9, b'Aluguel'), (10, b'Recurso humano'), (11, b'Outro')], default=11)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
