# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[(1, b'Agua'), (2, b'Luz'), (3, b'Material de limpeza'), (4, b'Papelaria'), (5, b'Mobilia'), (6, b'Seguran\xc3\xa7a'), (7, b'Manuten\xc3\xa7\xc3\xa3o'), (8, b'Regulamenta\xc3\xa7\xc3\xa3o'), (9, b'Aluguel'), (10, b'Recurso humano'), (11, b'Outro')], max_length=25)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
