# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos', '0003_auto_20161111_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.IntegerField(choices=[(1, b'Agua'), (2, b'Luz'), (3, b'Material de limpeza'), (4, b'Papelaria'), (5, b'Mobilia'), (6, b'Seguran\xc3\xa7a'), (7, b'Manuten\xc3\xa7\xc3\xa3o'), (8, b'Regulamenta\xc3\xa7\xc3\xa3o'), (9, b'Aluguel'), (10, b'Recurso humano'), (11, b'Outro')], default=11),
        ),
    ]
