# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos', '0004_auto_20161111_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
